### ISSUE TITLE
error while importing from telegram

### ISSUE THREAD

**Issue by lagemeet** [maunium/stickerpicker#34]
While importing any stickerpack i got this 
```
Reuploading 1179969546484711763..Traceback (most recent call last):
  File "/home/lagemeet/stickerpicker/.venv/lib/python3.7/site-packages/sticker/stickerimport.py", line 85, in reupload_pack
    reuploaded_documents[document.id] = already_uploaded[document.id]
KeyError: 1179969546484711763

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lagemeet/stickerpicker/.venv/bin/sticker-import", line 8, in <module>
    sys.exit(cmd())
  File "/home/lagemeet/stickerpicker/.venv/lib/python3.7/site-packages/sticker/stickerimport.py", line 164, in cmd
    asyncio.get_event_loop().run_until_complete(main(parser.parse_args()))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/lagemeet/stickerpicker/.venv/lib/python3.7/site-packages/sticker/stickerimport.py", line 156, in main
    await reupload_pack(client, pack, args.output_dir)
  File "/home/lagemeet/stickerpicker/.venv/lib/python3.7/site-packages/sticker/stickerimport.py", line 88, in reupload_pack
    reuploaded_documents[document.id] = await reupload_document(client, document)
  File "/home/lagemeet/stickerpicker/.venv/lib/python3.7/site-packages/sticker/stickerimport.py", line 38, in reupload_document
    mxc = await matrix.upload(data, "image/png", f"{document.id}.png")
  File "/home/lagemeet/stickerpicker/.venv/lib/python3.7/site-packages/sticker/lib/matrix.py", line 89, in upload
    return (await resp.json())["content_uri"]
KeyError: 'content_uri'

```

**Comment by zoenglinghou** [comment]
I have the same error. Did telegram change their APIs?

**Comment by tatsumoto-ren** [comment]
Any updates on this issue? It still persists.

**Comment by tulir** [comment]
That error means your homeserver's media repo is broken (e.g. the homeserver URL you entered doesn't route media requests correctly)

**Comment by bendschs** [comment]
same error came up for me, when i did not provide the full URL (including "https://") but just the domain name.

**Comment by tatsumoto-ren** [comment]
> That error means your homeserver's media repo is broken (e.g. the homeserver URL you entered doesn't route media requests correctly)

Thanks. After I switched to another homeserver, the error disappeared.

**Comment by TheRealKingS** [comment]
I solved this by replacing the auth token in config.json

**Comment by mohsenasm** [comment]
I had the same issue.
Refreshing the auth token (with a sign-out + sign-in) fixed this.
