### ISSUE TITLE
Installation on Windows now failing

### ISSUE THREAD

**Issue by pulpocaminante** [maunium/stickerpicker#52]
Seems to be an environment variable issue

```
amnesia ❯ git init .
Reinitialized existing Git repository in [ Truncated ]
                                                             
amnesia ❯ pip install .
Processing  [ Truncated ]\stickerpicker
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File " [ Truncated ]\stickerpicker\setup.py", line 3, in <module>
          from sticker.get_version import git_tag, git_revision, version, linkified_version
        File " [ Truncated ]\stickerpicker\sticker\get_version.py", line 9, in <module>
          "HOME": os.environ["HOME"],
        File " [ Truncated ]\Python\Python310\lib\os.py", line 680, in __getitem__
          raise KeyError(key) from None
      KeyError: 'HOME'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Lewko6702** [comment]
hey I was able to actually fix this!

change these two lines in setup.py and get_version.py 

get_version.py
`"HOME": os.environ["USERPROFILE"],`
and
setup.py
`long_desc = open("README.md", encoding="utf-8").read()`

this fixed it for me

**Comment by iraizo** [comment]
editing setup.py is required, but the home env variable you can just type 
```ps1
 $env:HOME = $env:USERPROFILE
```
beforehand

**Comment by Lewko6702** [comment]
ah yeah that is a much better solution
