### ISSUE TITLE
KeyError: 'content_uri'

### ISSUE THREAD

**Issue by Hagbear** [maunium/stickerpicker#56]
Hi,

i tried at a new folder and delete all the old stuff, but still i get the same error, with all packs i try. 
Why the script think it is already uploaded, the packs folder is empty. 
I am confused, what do i wrong?

```
(.venv) root@xxx:/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker# sticker-import https://t.me/addstickers/xxx
Reuploading XXX with 35 stickers and writing output to web/packs/xxx.json
Reuploading 5481252828116680717..Traceback (most recent call last):
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/lib/python3.9/site-packages/sticker/stickerimport.py", line 85, in reupload_pack
    reuploaded_documents[document.id] = already_uploaded[document.id]
KeyError: 5481252828116680717

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/bin/sticker-import", line 8, in <module>
    sys.exit(cmd())
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/lib/python3.9/site-packages/sticker/stickerimport.py", line 165, in cmd
    asyncio.get_event_loop().run_until_complete(main(parser.parse_args()))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/lib/python3.9/site-packages/sticker/stickerimport.py", line 157, in main
    await reupload_pack(client, pack, args.output_dir)
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/lib/python3.9/site-packages/sticker/stickerimport.py", line 88, in reupload_pack
    reuploaded_documents[document.id] = await reupload_document(client, document)
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/lib/python3.9/site-packages/sticker/stickerimport.py", line 38, in reupload_document
    mxc = await matrix.upload(data, "image/png", f"{document.id}.png")
  File "/var/lib/docker/volumes/docker_stickerpicker2/_data/stickerpicker/.venv/lib/python3.9/site-packages/sticker/lib/matrix.py", line 90, in upload
    return (await resp.json())["content_uri"]
KeyError: 'content_uri'
```

**Comment by tulir** [comment]
I think that happens if media uploads on your Matrix homeserver are broken

**Comment by Hagbear** [comment]
right! that it was. i generate a new access token and it works great again.
thank you very much :)

**Comment by RedEtherbloom** [comment]
Old issue, but according to my own testing this can also happen with servers that have rate-limiting enabled.

Had the same problem, after digging into the code it turned out the reason why there was no content_uri key was a 429(Too many requests) from the server.

I'm working on a PR at the moment that should address this issue.
