### ISSUE TITLE
where is token?

### ISSUE THREAD

**Issue by dearmin** [maunium/stickerpicker#57]
When I creative sticker from telegram,
It shows:
Homeserver URL: 
Access token: 

Where can I find " Access token"?

Thanks

**Comment by sebix** [comment]
You get your Telegram Token from the Telegram App

**Comment by dearmin** [comment]
> You get your Telegram Token from the Telegram App

I found the access token from element app
It pass
But import from telegram is failed.`Traceback (most recent call last):
  File "/usr/local/bin/sticker-import", line 8, in <module>
    sys.exit(cmd())
  File "/usr/local/lib/python3.10/dist-packages/sticker/stickerimport.py", line 165, in cmd
    asyncio.get_event_loop().run_until_complete(main(parser.parse_args()))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/sticker/stickerimport.py", line 157, in main
    await reupload_pack(client, pack, args.output_dir)
  File "/usr/local/lib/python3.10/dist-packages/sticker/stickerimport.py", line 65, in reupload_pack
    os.mkdir(os.path.dirname(pack_path))
FileNotFoundError: [Errno 2] No such file or directory: 'web/packs'
`

**Comment by peraperkan** [comment]
> > You get your Telegram Token from the Telegram App
> 
> I found the access token from element app It pass But import from telegram is failed.`Traceback (most recent call last): File "/usr/local/bin/sticker-import", line 8, in <module> sys.exit(cmd()) File "/usr/local/lib/python3.10/dist-packages/sticker/stickerimport.py", line 165, in cmd asyncio.get_event_loop().run_until_complete(main(parser.parse_args())) File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete return future.result() File "/usr/local/lib/python3.10/dist-packages/sticker/stickerimport.py", line 157, in main await reupload_pack(client, pack, args.output_dir) File "/usr/local/lib/python3.10/dist-packages/sticker/stickerimport.py", line 65, in reupload_pack os.mkdir(os.path.dirname(pack_path)) FileNotFoundError: [Errno 2] No such file or directory: 'web/packs' `

I get the same error as you. Did you manage to find the solution to the problem?
