### ISSUE TITLE
AttributeError: 'StickerSet' object has no attribute 'animated'

### ISSUE THREAD

**Issue by Hagbear** [maunium/stickerpicker#74]
Hi,

since a few days i get the following error, if i try to import a pack.

```
Traceback (most recent call last):
  File "/usr/local/bin/sticker-import", line 8, in <module>
    sys.exit(cmd())
  File "/usr/local/lib/python3.9/site-packages/sticker/stickerimport.py", line 165, in cmd
    asyncio.get_event_loop().run_until_complete(main(parser.parse_args()))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/sticker/stickerimport.py", line 157, in main
    await reupload_pack(client, pack, args.output_dir)
  File "/usr/local/lib/python3.9/site-packages/sticker/stickerimport.py", line 59, in reupload_pack
    if pack.set.animated:
AttributeError: 'StickerSet' object has no attribute 'animated'
```

I thought maybe is was a problem with my new python version, so i put in a docker container with python3.9 but i get the same error. Has telegram change some infos in their packs?

Greetings Marian

**Comment by Hagbear** [comment]
i comment out
```
    if pack.set.animated:
        print("Animated stickerpacks are currently not supported")
        return
```
on file sticker/stickerimport.py
and now it works again. but maybe not the best solution.

**Comment by Fangliding** [comment]
same question

**Comment by mistydemeo** [comment]
Looks like this was fixed in 125d057e447ef62fddbcda40c8ea4c7faee7082a.
