### ISSUE TITLE
Telegram sticker packs with animated stickers fail to import

### ISSUE THREAD

**Issue by Azel04** [maunium/stickerpicker#79]
Attempting to import any Telegram Sticker Pack with an animated sticker results in this error

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/REDACTED/stickerpicker/.venv/bin/sticker-import", line 8, in <module>
    sys.exit(cmd())
             ^^^^^
  File "/home/REDACTED/stickerpicker/.venv/lib/python3.12/site-packages/sticker/stickerimport.py", line 161, in cmd
    asyncio.get_event_loop().run_until_complete(main(parser.parse_args()))
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/REDACTED/stickerpicker/.venv/lib/python3.12/site-packages/sticker/stickerimport.py", line 153, in main
    await reupload_pack(client, pack, args.output_dir)
  File "/home/REDACTED/stickerpicker/.venv/lib/python3.12/site-packages/sticker/stickerimport.py", line 84, in reupload_pack
    reuploaded_documents[document.id] = await reupload_document(client, document)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/REDACTED/stickerpicker/.venv/lib/python3.12/site-packages/sticker/stickerimport.py", line 36, in reupload_document
    data, width, height = util.convert_image(data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/REDACTED/stickerpicker/.venv/lib/python3.12/site-packages/sticker/lib/util.py", line 28, in convert_image
    image: Image.Image = Image.open(BytesIO(data)).convert("RGBA")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/REDACTED/stickerpicker/.venv/lib/python3.12/site-packages/PIL/Image.py", line 3498, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x74c06caf7600>`

**Comment by robertototaro** [comment]
I can reproduce this problem with other Telegram sticker packs, for example:
https://t.me/addstickers/Hedgehoge
https://t.me/addstickers/NickWallowPig
https://t.me/addstickers/MooingCow

**Comment by Azel04** [comment]
After quickly looking into the code, i think there may be a way to fix this.

Animated Telegram Stickers use the WEBM format which apparently isn't compatible with the image conversion library used here.

Maybe we can convert WEBM to another format like GIF with FFMpeg? Or maybe we can change the image conversion library to another one that supports WEBM.

**Comment by 3ttercap** [comment]
> After quickly looking into the code, i think there may be a way to fix this.
> 
> Animated Telegram Stickers use the WEBM format which apparently isn't compatible with the image conversion library used here.
> 
> Maybe we can convert WEBM to another format like GIF with FFMpeg? Or maybe we can change the image conversion library to another one that supports WEBM.

yes, I used pylottie, playwright, Pillow at https://pypi.org/project/pyrlottie/ which help converting the .tgs sticker file to .gif file, which could be used here right?

**Comment by mah3uz** [comment]
I am getting the same issue. 
Trying to experiment if I can convert the animated image. But hitting on wall when try to get image type from telegram download.
Here it's getting the data as bytes data. And it's giving mime type `application/gzip`

No Idea how to determine the image type.

**Comment by msrd0** [comment]
You can try using https://github.com/luckyturtledev/mstickereditor, it can also import stickers compatible with this repository and I hacked webm support (using ffmpeg) into that one a while ago.

**Comment by mah3uz** [comment]
@msrd0 Thank you mentioning that, I am already using that tool, working as charm.
